<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-latest.js"></script>
	<link rel="icon" href="../img/favicon.ico">
	<script src="../irArriba.js"></script>
	<script src="../js/abrirNav.js" defer></script>
	<title>Tooth decay: what are they, causes and treatments</title>
	<!-- LINK CSS -->
	<link rel="stylesheet" type="text/css" href="../css/styles.css">
	<link rel="stylesheet" type="text/css" href="../css/IndexBlog.css">
	<link rel="stylesheet" href="../bootstrap-5.0.2-dist/css/bootstrap.min.css">
	<!-- LINK ICONOS-->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
	<span class="ir-arriba icon-arrow-up2">↑</span>
	<header class="hero-blog">
		<!-- MENU NAVEGACIÓN -->
		<nav class="menu">
			<label class="logo"><img src="https://i.imgur.com/uGFKsa7.png" alt="logo"> White & Pink Dental</label>
			<ul class="menu_items">
				<li><a href="index.php">Home</a></li>
				<li><a href="services.php">Services</a></li>
				<li><a href="blog-home-page.php">Blog</a></li>
				<li><a href="our-staff.php">Staff</a></li>
				<li class="colorear"><a href="find-us.php" class="link-active">Find us</a></li>
			</ul>

			<span class="btn_menu">
				<i class="fa fa-bars"></i>
			</span>
		</nav>
		<div class="divLang">
			<ul class="ulLang">
				<li class="liLang">
					<a href="../caries.html" class="aLang"><i class="fa-solid fa-globe"></i>ESPAÑOL</a>
				</li>
			</ul>
		</div>
		<section class="menu-blog">
			<div class="hero-textos">

			</div>

		</section>
	</header>
	<!-- SECTION MAIN -->
	<main>
		<span class="ir-arriba icon-arrow-up2">↑</span>
		<a href="https://api.whatsapp.com/send?phone=523221170846&text=Hello! I want assistance." class="btn-wsp" target="_blank"><i class="fab fa-whatsapp"></i></a>
		<!-- SECTION TEMA BLOG -->
		<section class="temas-blog contenedor">
			<div class="contenido-post">
				<div class="titulo-blog">
					<h1>Tooth decay: what are they, causes and treatments</h1>
					<h3>Posted by Luis Fernando Montaño Chavez | <span>Nov 17, 2021</span></h3>
					<p>Cavities, our archenemies of all life. From children to adults.</p>
					<div class="linea-img">
						<img src="https://bqdentalcenters.es/wp-content/uploads/tipos-de-caries-palas-centrales.jpg">
					</div>
				</div>
				<div class="info-post-blog">
					<hr>
					<h2 id="subtitulo1">WHAT ARE THEY</h2>
					<p>Cavities are permanently damaged areas on the surface of the teeth that develop into small openings or holes. Cavities occur due to a combination of factors, including bacteria in the mouth, frequent snacking, sugary drinks, and poor dental cleaning.</p>
					<br>
					<p>Dental cavities are one of the most common health problems in the world. They appear especially frequently in children, adolescents and older adults. However, everyone who has teeth can get cavities, even babies.</p>
					<br>
					<p>If left untreated, cavities can spread and affect deeper layers of the teeth. They can cause severe toothache, infections, and tooth loss. The best protection measures against tooth decay are regular dental visits and good brushing and flossing habits.</p>
					<br>
					<hr>
					<h2 id="subtitulo2">CAUSES</h2>
					<p>Dental cavities are a process that occurs over time. This is how dental cavities form:
						<br>
						<br>
						<span><b>° Plaque formation.</b></span> Dental plaque is a transparent sticky film that covers the teeth. It is generated by eating a lot of sugars and starches and not brushing your teeth well. When sugars and starches are not cleaned from your teeth, bacteria quickly begin to feed on them and form plaque. Plaque that remains on the teeth can harden below or above the gum line and turn into tartar. Tartar makes it harder to remove plaque and creates a shield for bacteria.
						<br>
						<br>
						<span><b>° Plaque attacks.</b></span> The acids in plaque remove minerals from the hard, outer enamel of teeth. This erosion causes tiny openings or holes in the enamel, the first stage of cavities. Once parts of the enamel are worn away, bacteria and acid reach the next layer of the teeth, called "dentin." This layer is softer than enamel and less resistant to acid. The dentin has small tubes that communicate directly with the nerve of the tooth and cause sensitivity.
						<br>
						<br>
						<span><b>° The destruction continues.</b></span> As dental cavities form, bacteria and acid continue their march through the teeth, then moving to the material inside the tooth ( pulp) containing nerves and blood vessels. The pulp becomes inflamed and irritated by bacteria. Since there is no room for inflammation to expand inside a tooth, the nerve is squeezed, causing pain. The discomfort can even extend outside the root of the tooth, towards the bone.
					</p>
					<br>
					<br>
					<img src="https://images.pexels.com/photos/298611/pexels-photo-298611.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940">
					<br>
					<hr>
					<h2 id="subtitulo3">TREATMENT</h2>
					<p>Regular checkups can identify cavities and other dental diseases before they cause troublesome symptoms and lead to more serious problems. The sooner you seek medical attention, the more likely you are to reverse the early stages of tooth decay and prevent it from progressing. If a cavity is treated before it starts to cause pain, you probably won't need long-term treatment.
						<br><br>
						Caries treatment depends on the severity and your particular situation. Some treatment options are as follows:
						<br><br>
						<span><b>° Fluoride treatments.</b></span> If a cavity is just starting to appear, fluoride treatment can help restore tooth enamel and sometimes reverse the decay in the tooth. very early stages. Professional fluoride treatments contain more fluoride than the amount found in tap water, toothpaste, and mouthwash. Fluoride treatments can be liquid, gel, foam, or varnish that is brushed onto the teeth or placed in a small tray that fits over the teeth.
						<br><br>
						<span><b>° Fillings.</b></span> Fillings, sometimes called “restorations”, are the main treatment option when decay has progressed beyond the first stage. Fillings are made from various materials, such as tooth-colored composite resins, porcelain, or dental amalgam, which is a combination of different materials.
						<br><br>
						<span><b>° Crowns.</b></span> If you have extensive cavities or weakened teeth, you may need a crown – a custom-made covering that replaces the entire natural crown of the tooth. The dentist will drill the decayed area and other parts of the tooth to ensure a good fit. Crowns can be made of gold, high-strength porcelain, resin, porcelain-fused-to-metal, or other materials.
						<br><br>
						<span><b>° Root Canals.</b></span> When decay reaches the inside of the tooth (pulp), you may need root canals. This is a treatment to repair and preserve a badly damaged or infected tooth instead of extracting it. The pulp of the diseased tooth is extracted. Medicines are sometimes put into the root canal to clean out the infection. The pulp is then replaced with a filling.
						<br><br>
						<span><b>° Tooth extraction.</b></span> Some teeth have such severe decay that they cannot be restored and must be extracted. Tooth extraction can leave a gap that causes other teeth to shift. If possible, consider getting a bridge or dental implant to replace the missing tooth.
					</p>
					<br>
					<br>
					<img src="https://images.pexels.com/photos/6812536/pexels-photo-6812536.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940">
				</div>
				<!-- SECTION TEMARIO -->

			</div>
			<div class="temario-blog">
				<h1>TEMARY</h1>
				<br>
				<ul class="temario">
					<li class="temario-item"><a href="#subtitulo1" class="temario-link">WHAT ARE THEY</a></li>
					<li class="temario-item"><a href="#subtitulo2" class="temario-link">CAUSES</a></li>
					<li class="temario-item"><a href="#subtitulo3" class="temario-link">TREATMENT</a></li>
				</ul>
				<div class="card-autor-blog">
					<h2>About the Author</h2>
					<h5>Luis F. Montaño - Frontend and Backend Developer.</h5>
					<p>Last edition: Nov 20, 2021</p>
					<div class="linea-card-autor"></div>
					<h1>Social media:</h1>
					<a href="https://www.facebook.com/LuisFMC19/" class="text-white text-decoration-none text-muted fs-4 			me-4" target="_blank">
						<i class='fab fa-facebook-f'></i>
					</a>
					<a href="https://www.instagram.com/apocosi_rey/" class="text-white text-decoration-none text-muted fs-4 me-4" target="_blank">
						<i class="fab fa-instagram"></i>
					</a>
					<a href="https://twitter.com/apocosi_rey" class="text-white text-decoration-none text-muted fs-4 			me-4" target="_blank">
						<i class="fab fa-twitter"></i>
					</a>
					<a href="https://github.com/MadeOfDarkness" class="text-white text-decoration-none text-muted fs-4 			me-4" target="_blank">
						<i class="fab fa-github"></i>
					</a>
				</div>
			</div>
		</section>
	</main>

	<!-- FOOTER -->
	<footer class="bg-dark py-5" id="subscribed">
		<div class="container">
			<div class="row text-white g-4">
				<div class="col-md-6 col-lg-3">
					<a class="text-uppercase text-decoration-none brand text-white" href="index.php">White & Pink Dental &copy;</a>
					<p class="text-white text-muted mt-3">The best option to invest in your oral health.</p>
					<img src="https://i.imgur.com/vidg8Ci.png" style="width: auto; height: 125px;" class="iconoFooter">
				</div>

				<div class="col-md-6 col-lg-3">
					<h5 class="fw-light">Links</h5>
					<ul class="list-unstyled">
						<li class="my-3">
							<a href="index.php" class="text-white text-decoration-none text-muted">
								<i class="fas fa-chevron-right me-1"></i>Home
							</a>
						</li>
						<li class="my-3">
							<a href="services.php" class="text-white text-decoration-none text-muted">
								<i class="fas fa-chevron-right me-1"></i>Services
							</a>
						</li>
						<li class="my-3">
							<a href="blog-home-page.php" class="text-white text-decoration-none text-muted">
								<i class="fas fa-chevron-right me-1"></i>Blog
							</a>
						</li>
						<li class="my-3">
							<a href="our-staff.php" class="text-white text-decoration-none text-muted">
								<i class="fas fa-chevron-right me-1"></i>Staff
							</a>
						</li>
					</ul>
				</div>

				<div class="col-md-6 col-lg-3">
					<h5 class="fw-light mb-3">Find us</h5>
					<div class="d-flex justify-content-start align-items-start my-2 text-muted">
						<span class="me-3">
							<i class="fas fa-map-marked-alt"></i>
						</span>
						<span class="fw-light">
							<a href="https://www.google.com/maps/dir/20.6840134,-105.2077802/20.6543903,-105.2254639/@20.672498,-105.2338262,14z/data=!3m1!4b1!4m4!4m3!1m1!4e1!1m0" target="_blank" class="fw-light" style="color: #666f77;">Avenida Grandes Lagos 303 Local 28 48312 Puerto Vallarta, Jalisco, Mexico</a>
						</span>
					</div>
					<div class="d-flex justify-content-start align-items-start my-2 text-muted">
						<span class="me-3">
							<i class="fas fa-clock"></i>
						</span>
						<span class="fw-light">
							°Monday to Friday - 9:00 a.m. to 2:00 p.m. | 4:00 p.m. to 8:00 p.m. <br>°Saturday - 9:00 a.m. to 2:00 p.m. <br>°Sunday - Closed
						</span>
					</div>
					<div class="d-flex justify-content-start align-items-start my-2 text-muted">
						<span class="me-3">
							<i class="fas fa-phone-alt"></i>
						</span>
						<span class="fw-light">
							<a href="tel:322 224 1758" class="fw-light" style="color: #666f77;">322 224 1758</a>
						</span>
					</div>
				</div>

				<div class="col-md-6 col-lg-3">
					<h5 class="fw-light mb-3">Social media</h5>
					<div>
						<ul class="list-unstyled d-flex">
							<li>
								<a href="https://www.facebook.com/dentalwhitelinepv" class="text-white text-decoration-none text-muted fs-4 me-4" target="_blank">
									<i class="fab fa-facebook-f"></i>
								</a>
							</li>
							<li>
								<a href="https://www.instagram.com/whiteandpink.dental/" class="text-white text-decoration-none text-muted fs-4 me-4" target="_blank">
									<i class="fab fa-instagram"></i>
								</a>
							</li>
							<li>
								<a href="https://api.whatsapp.com/send?phone=523221170846&app=facebook&entry_point=page_cta&fbclid=IwAR3g7ltELvHFM8mWuMfHv2ARQQubeVLJ3vAIaVBJR_Aokg13GlOAeb_b2Xw" class="text-white text-decoration-none text-muted fs-4 me-4" target="_blank">
									<i class="fab fa-whatsapp"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<div style="background-color: black; color:gray; text-align: center;">Copyright &copy; 2022 - White & Pink Dental | All rights reserved |
		<a href="privacy-policy.php" class="fw-light" style="color: #666f77;"> Privacy Policy</a>
	</div>
	<!-- Isotope js-->
	<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
	<!-- Bootstrap js -->
	<script src="../bootstrap-5.0.2-dist/js/bootstrap.min.js"></script>
	<!-- Jquery -->
	<script src="../js/jquery-3.6.0.js"></script>
	<!-- custom js -->
	<script src="../js/script.js"></script>
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script>
		AOS.init();
	</script>
</body>

</html>